import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'tr' | 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
  tr: {
    'dashboard': 'Ana Sayfa',
    'content': 'İçerik',
    'content_library': 'İçerik Kütüphanesi',
    'ai_generation': 'AI Üretim',
    'lesson_plans': 'Ders Planları',
    'lesson_templates': 'Ders Şablonları',
    'lessons': 'Ders Planları',
    'assignments': 'Ödevler',
    'questions': 'Sorular',
    'question_generator': 'Soru Üreteci',
    'question_bank': 'Soru Bankası',
    'exams': 'Sınavlar',
    'exam_list': 'Sınav Listesi',
    'exam_management': 'Sınav Yönetimi',
    'grading': 'Notlandırma',
    'analytics': 'Analitik',
    'student_progress': 'Öğrenci İlerlemesi',
    'learning_style': 'Öğrenme Stili',
    'classroom_dashboard': 'Sınıf Paneli',
    'ai_assistants': 'AI Asistanları',
    'writing_assistant': 'Yazma Asistanı',
    'project_analysis': 'Proje Analizi',
    'file_refactor': 'Kod Düzenleme',
    'auto_module_generator': 'Otomatik Modül Üretici',
    'gamification': 'Oyunlaştırma',
    'admin': 'Yönetim',
    'settings': 'Ayarlar',
    'logout': 'Çıkış Yap',
    'profile': 'Profil',
    'my_profile': 'Profilim',
    'welcome': 'Hoş Geldiniz',
    'login': 'Giriş Yap',
    'quick_actions': 'Hızlı Erişim',
    'new_quiz': 'Yeni Quiz',
    'new_lesson_plan': 'Yeni Ders Planı',
    'upload_content': 'İçerik Yükle',
    'my_assignments': 'Ödevlerim',
    'my_progress': 'İlerlemem',
    'advancedQuestionGenerator': 'Gelişmiş Soru Üretici',
    'selectQuestionTypes': 'Soru Tiplerini Seç',
    'selectMultipleQuestionTypes': 'Birden fazla soru tipi seçin',
    'selected': 'Seçilen',
    'questionTypes': 'Soru Tipleri',
    'difficultyLevel': 'Zorluk Seviyesi',
    'selectDifficulty': 'Zorluk seçin',
    'generateQuestions': 'Soru Üret',
    'reset': 'Sıfırla',
    'preview': 'Önizleme',
    'selectedQuestionTypes': 'Seçili Soru Tipleri',
    'difficulty': 'Zorluk',
    'notSelected': 'Seçilmedi',
    'loading': 'Yükleniyor',
    'error': 'Hata',
    'chooseContentCreationMode': 'İçerik Oluşturma Modunu Seç',
    'selectHowYouWantToCreateQuestions': 'Soruları nasıl oluşturmak istediğinizi seçin',
    'manualCreation': 'Manuel Oluşturma',
    'manualCreationDesc': 'Yazarlar, öğretmenler tarafından geleneksel araçlarla oluşturulan içerik',
    'aiAssisted': 'AI Destekli',
    'aiAssistedDesc': 'AI tarafından üretilen veya geliştirilen, insan denetimli içerik',
    'hybrid': 'Hibrit (AI + Manuel)',
    'hybridDesc': 'AI taslak oluşturur, insan düzenler ve iyileştirir',
    'fullEditor': 'Tam Düzenleyici',
    'richFormatting': 'Zengin Biçimlendirme',
    'mediaUpload': 'Medya Yükleme',
    'versionControl': 'Versiyon Kontrolü',
    'collaboration': 'İşbirliği',
    'teachers': 'Öğretmenler',
    'authors': 'Yazarlar',
    'editors': 'Editörler',
    'aiGeneration': 'AI Üretimi',
    'autoQuestions': 'Otomatik Sorular',
    'smartSuggestions': 'Akıllı Öneriler',
    'bulkCreation': 'Toplu Oluşturma',
    'pdfExtraction': 'PDF Çıkarma',
    'contentManagers': 'İçerik Yöneticileri',
    'aiDraft': 'AI Taslağı',
    'manualEdit': 'Manuel Düzenleme',
    'iterativeImprovement': 'Yinelemeli İyileştirme',
    'bestOfBoth': 'Her İkisinin En İyisi',
    'powerUsers': 'İleri Kullanıcılar',
    'contentTeams': 'İçerik Ekipleri',
    'features': 'Özellikler',
    'idealFor': 'İçin İdeal',
    'startCreating': 'Oluşturmaya Başla',
    'comparisonTable': 'Karşılaştırma Tablosu',
    'feature': 'Özellik',
    'manual': 'Manuel',
    'creationSpeed': 'Oluşturma Hızı',
    'qualityControl': 'Kalite Kontrolü',
    'learningCurve': 'Öğrenme Eğrisi',
    'medium': 'Orta',
    'easy': 'Kolay',
    'bulkGeneration': 'Toplu Üretim',
    'customization': 'Özelleştirme',
    'recommended': 'Önerilen',
    'contentManagement': 'İçerik Yönetimi',
    'uploadContent': 'İçerik Yükle',
    'mediaLibrary': 'Medya Kütüphanesi',
    'questionsAndExams': 'Sorular & Sınavlar',
    'createQuestion': 'Soru Oluştur',
    'questionBank': 'Soru Bankası',
    'teachingAndLearning': 'Öğretim & Öğrenme',
    'curriculumSettings': 'Müfredat Ayarları',
    'analyticsAndReports': 'Analitik & Raporlar',
    'performanceReports': 'Performans Raporları',
    'aiTools': 'AI Araçları',
    'aiQuestionGenerator': 'AI Soru Üretici',
    'aiContentGenerator': 'AI İçerik Üretici',
    'aiQuickGenerate': 'AI Hızlı Üret',
    'administration': 'Yönetim',
    'curriculumManagement': 'Müfredat Yönetimi',
    'financeAndLicenses': 'Finans & Lisanslar',
    'royaltyManagement': 'Telif Yönetimi',
    'systemSettings': 'Sistem Ayarları',
    'new_exam': 'Yeni Sınav',
    'menuLoadFailed': 'Menü yüklenemedi',
    'user_management': 'Kullanıcı Yönetimi',
    'tenant_management': 'Tenant Yönetimi',
    'tenants': 'Tenantlar',
    'tenant_settings': 'Tenant Ayarları',
    'users': 'Kullanıcılar',
    'roles_permissions': 'Rol & Yetkiler',
    'departments': 'Departmanlar',
    'curriculum_management': 'Müfredat Yönetimi',
    'subjects': 'Dersler',
    'topics': 'Konular',
    'grades': 'Sınıflar',
    'system_management': 'Sistem Yönetimi',
    'system_definitions': 'Sistem Tanımları',
    'ai_configuration': 'AI Yapılandırma',
    'audit_logs': 'İşlem Logları',
    'presentations': 'Sunumlar',
    'presentation_list': 'Sunum Listesi',
    'presentation_builder': 'Sunum Oluşturucu',
    'courses': 'Kurslar',
    'certificates': 'Sertifikalar',
    'finance': 'Finans',
    'overview': 'Genel Bakış',
    'cash_management': 'Kasa Yönetimi',
    'transactions': 'İşlemler',
    'budgets': 'Bütçeler',
    'per_diem': 'Harcırahlar',
    'payment_gateways': 'Ödeme Sistemleri',
    'payments': 'Ödemeler',
    'subscriptions': 'Abonelikler',
    'invoices': 'Faturalar',
    'licenses': 'Lisanslar',
    'license_packages': 'Lisans Paketleri',
    'royalty_management': 'Telif Yönetimi',
    'author_dashboard': 'Yazar Paneli',
    'royalty_reports': 'Telif Raporları',
    'contracts': 'Sözleşmeler',
    'communication': 'İletişim',
    'parent_portal': 'Veli Portalı',
    'integrations': 'Entegrasyonlar',
    'lti_integration': 'LTI Entegrasyonu',
    'api_management': 'API Yönetimi',
    'monitoring': 'İzleme',
    'locations': 'Lokasyonlar',
    'classroom': 'Sınıf Paneli',
    'exam_monitoring': 'Sınav İzleme',
    'finance_dashboard': 'Finans Özeti',
    'notifications': 'Bildirimler',
    'reports': 'Raporlar',
    'loading': 'Yükleniyor...',
    'save': 'Kaydet',
    'cancel': 'İptal',
    'delete': 'Sil',
    'edit': 'Düzenle',
    'search': 'Ara...',
    'filter': 'Filtrele',
    'all': 'Tümü',
    'active': 'Aktif',
    'inactive': 'İnaktif',
    'draft': 'Taslak',
    'published': 'Yayında',
    'archived': 'Arşiv',
  },
  en: {
    'dashboard': 'Dashboard',
    'content': 'Content',
    'content_library': 'Content Library',
    'ai_generation': 'AI Generation',
    'lesson_plans': 'Lesson Plans',
    'lesson_templates': 'Lesson Templates',
    'lessons': 'Lesson Plans',
    'assignments': 'Assignments',
    'questions': 'Questions',
    'exams': 'Exams',
    'analytics': 'Analytics',
    'student_progress': 'Student Progress',
    'learning_style': 'Learning Style',
    'classroom_dashboard': 'Classroom Dashboard',
    'ai_assistants': 'AI Assistants',
    'writing_assistant': 'Writing Assistant',
    'project_analysis': 'Project Analysis',
    'file_refactor': 'Code Refactoring',
    'auto_module_generator': 'Auto Module Generator',
    'gamification': 'Gamification',
    'admin': 'Administration',
    'settings': 'Settings',
    'logout': 'Logout',
    'profile': 'Profile',
    'my_profile': 'My Profile',
    'welcome': 'Welcome',
    'login': 'Login',
    'quick_actions': 'Quick Actions',
    'new_quiz': 'New Quiz',
    'new_lesson_plan': 'New Lesson Plan',
    'upload_content': 'Upload Content',
    'my_assignments': 'My Assignments',
    'my_progress': 'My Progress',
    'advancedQuestionGenerator': 'Advanced Question Generator',
    'selectQuestionTypes': 'Select Question Types',
    'selectMultipleQuestionTypes': 'Select multiple question types',
    'selected': 'Selected',
    'questionTypes': 'Question Types',
    'difficultyLevel': 'Difficulty Level',
    'selectDifficulty': 'Select difficulty',
    'generateQuestions': 'Generate Questions',
    'reset': 'Reset',
    'preview': 'Preview',
    'selectedQuestionTypes': 'Selected Question Types',
    'difficulty': 'Difficulty',
    'notSelected': 'Not Selected',
    'loading': 'Loading',
    'error': 'Error',
    'chooseContentCreationMode': 'Choose Content Creation Mode',
    'selectHowYouWantToCreateQuestions': 'Select how you want to create questions',
    'manualCreation': 'Manual Creation',
    'manualCreationDesc': 'Content created by authors using traditional tools',
    'aiAssisted': 'AI Assisted',
    'aiAssistedDesc': 'Content generated by AI with human review',
    'hybrid': 'Hybrid (AI + Manual)',
    'hybridDesc': 'AI generates draft, human refines',
    'fullEditor': 'Full Editor',
    'richFormatting': 'Rich Formatting',
    'mediaUpload': 'Media Upload',
    'versionControl': 'Version Control',
    'collaboration': 'Collaboration',
    'teachers': 'Teachers',
    'authors': 'Authors',
    'editors': 'Editors',
    'aiGeneration': 'AI Generation',
    'autoQuestions': 'Auto Questions',
    'smartSuggestions': 'Smart Suggestions',
    'bulkCreation': 'Bulk Creation',
    'pdfExtraction': 'PDF Extraction',
    'contentManagers': 'Content Managers',
    'aiDraft': 'AI Draft',
    'manualEdit': 'Manual Edit',
    'iterativeImprovement': 'Iterative Improvement',
    'bestOfBoth': 'Best of Both',
    'powerUsers': 'Power Users',
    'contentTeams': 'Content Teams',
    'features': 'Features',
    'idealFor': 'Ideal For',
    'startCreating': 'Start Creating',
    'comparisonTable': 'Comparison Table',
    'feature': 'Feature',
    'manual': 'Manual',
    'creationSpeed': 'Creation Speed',
    'qualityControl': 'Quality Control',
    'learningCurve': 'Learning Curve',
    'medium': 'Medium',
    'easy': 'Easy',
    'bulkGeneration': 'Bulk Generation',
    'customization': 'Customization',
    'recommended': 'Recommended',
    'contentManagement': 'Content Management',
    'uploadContent': 'Upload Content',
    'mediaLibrary': 'Media Library',
    'questionsAndExams': 'Questions & Exams',
    'createQuestion': 'Create Question',
    'questionBank': 'Question Bank',
    'teachingAndLearning': 'Teaching & Learning',
    'curriculumSettings': 'Curriculum Settings',
    'analyticsAndReports': 'Analytics & Reports',
    'performanceReports': 'Performance Reports',
    'aiTools': 'AI Tools',
    'aiQuestionGenerator': 'AI Question Generator',
    'aiContentGenerator': 'AI Content Generator',
    'aiQuickGenerate': 'AI Quick Generate',
    'administration': 'Administration',
    'curriculumManagement': 'Curriculum Management',
    'financeAndLicenses': 'Finance & Licenses',
    'royaltyManagement': 'Royalty Management',
    'systemSettings': 'System Settings',
    'new_exam': 'New Exam',
    'user_management': 'User Management',
    'tenant_management': 'Tenant Management',
    'tenants': 'Tenants',
    'tenant_settings': 'Tenant Settings',
    'users': 'Users',
    'roles_permissions': 'Roles & Permissions',
    'departments': 'Departments',
    'curriculum_management': 'Curriculum Management',
    'subjects': 'Subjects',
    'topics': 'Topics',
    'grades': 'Grades',
    'system_management': 'System Management',
    'system_definitions': 'System Definitions',
    'ai_configuration': 'AI Configuration',
    'audit_logs': 'Audit Logs',
    'presentations': 'Presentations',
    'presentation_list': 'Presentation List',
    'presentation_builder': 'Presentation Builder',
    'courses': 'Courses',
    'certificates': 'Certificates',
    'finance': 'Finance',
    'overview': 'Overview',
    'cash_management': 'Cash Management',
    'transactions': 'Transactions',
    'budgets': 'Budgets',
    'per_diem': 'Per Diem',
    'payment_gateways': 'Payment Gateways',
    'payments': 'Payments',
    'subscriptions': 'Subscriptions',
    'invoices': 'Invoices',
    'licenses': 'Licenses',
    'license_packages': 'License Packages',
    'royalty_management': 'Royalty Management',
    'author_dashboard': 'Author Dashboard',
    'royalty_reports': 'Royalty Reports',
    'contracts': 'Contracts',
    'communication': 'Communication',
    'parent_portal': 'Parent Portal',
    'integrations': 'Integrations',
    'lti_integration': 'LTI Integration',
    'api_management': 'API Management',
    'monitoring': 'Monitoring',
    'locations': 'Locations',
    'classroom': 'Classroom',
    'exam_monitoring': 'Exam Monitoring',
    'finance_dashboard': 'Finance Overview',
    'notifications': 'Notifications',
    'reports': 'Reports',
    'loading': 'Loading...',
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'search': 'Search...',
    'filter': 'Filter',
    'all': 'All',
    'active': 'Active',
    'inactive': 'Inactive',
    'draft': 'Draft',
    'published': 'Published',
    'archived': 'Archived',
  },
  ar: {
    'dashboard': 'لوحة القيادة',
    'content': 'المحتوى',
    'content_library': 'مكتبة المحتوى',
    'ai_generation': 'إنشاء بالذكاء الاصطناعي',
    'lesson_plans': 'خطط الدروس',
    'lesson_templates': 'قوالب الدروس',
    'lessons': 'خطط الدروس',
    'assignments': 'الواجبات',
    'questions': 'الأسئلة',
    'exams': 'الامتحانات',
    'analytics': 'التحليلات',
    'student_progress': 'تقدم الطالب',
    'learning_style': 'نمط التعلم',
    'classroom_dashboard': 'لوحة تحكم الفصل',
    'ai_assistants': 'مساعدو الذكاء الاصطناعي',
    'writing_assistant': 'مساعد الكتابة',
    'project_analysis': 'تحليل المشروع',
    'file_refactor': 'إعادة هيكلة الكود',
    'auto_module_generator': 'مولد الوحدات التلقائي',
    'gamification': 'اللعب',
    'admin': 'الإدارة',
    'settings': 'الإعدادات',
    'logout': 'تسجيل خروج',
    'profile': 'الملف الشخصي',
    'my_profile': 'ملفي الشخصي',
    'welcome': 'مرحباً',
    'login': 'تسجيل الدخول',
    'quick_actions': 'الإجراءات السريعة',
    'new_quiz': 'اختبار جديد',
    'new_lesson_plan': 'خطة درس جديدة',
    'upload_content': 'تحميل محتوى',
    'my_assignments': 'واجباتي',
    'my_progress': 'تقدمي',
    'advancedQuestionGenerator': 'مولد الأسئلة المتقدم',
    'selectQuestionTypes': 'حدد أنواع الأسئلة',
    'selectMultipleQuestionTypes': 'حدد أنواع أسئلة متعددة',
    'selected': 'المحدد',
    'questionTypes': 'أنواع الأسئلة',
    'difficultyLevel': 'مستوى الصعوبة',
    'selectDifficulty': 'حدد الصعوبة',
    'generateQuestions': 'توليد الأسئلة',
    'reset': 'إعادة تعيين',
    'preview': 'معاينة',
    'selectedQuestionTypes': 'أنواع الأسئلة المحددة',
    'difficulty': 'الصعوبة',
    'notSelected': 'غير محدد',
    'loading': 'جاري التحميل',
    'error': 'خطأ',
    'user_management': 'إدارة المستخدمين',
    'tenant_management': 'إدارة المستأجرين',
    'tenants': 'المستأجرون',
    'tenant_settings': 'إعدادات المستأجر',
    'users': 'المستخدمون',
    'roles_permissions': 'الأدوار والصلاحيات',
    'departments': 'الأقسام',
    'curriculum_management': 'إدارة المناهج',
    'subjects': 'المواد',
    'topics': 'المواضيع',
    'grades': 'الصفوف',
    'system_management': 'إدارة النظام',
    'system_definitions': 'تعريفات النظام',
    'ai_configuration': 'تكوين الذكاء الاصطناعي',
    'audit_logs': 'سجلات التدقيق',
    'presentations': 'العروض التقديمية',
    'presentation_list': 'قائمة العروض',
    'presentation_builder': 'منشئ العروض',
    'courses': 'الدورات',
    'certificates': 'الشهادات',
    'finance': 'المالية',
    'payments': 'المدفوعات',
    'subscriptions': 'الاشتراكات',
    'invoices': 'الفواتير',
    'licenses': 'التراخيص',
    'license_packages': 'حزم التراخيص',
    'royalty_management': 'إدارة حقوق الملكية',
    'author_dashboard': 'لوحة المؤلف',
    'royalty_reports': 'تقارير حقوق الملكية',
    'contracts': 'العقود',
    'communication': 'التواصل',
    'parent_portal': 'بوابة أولياء الأمور',
    'integrations': 'التكاملات',
    'lti_integration': 'تكامل LTI',
    'monitoring': 'المراقبة',
    'locations': 'المواقع',
    'reports': 'التقارير',
    'loading': 'جار التحميل...',
    'save': 'حفظ',
    'cancel': 'إلغاء',
    'delete': 'حذف',
    'edit': 'تعديل',
    'search': 'بحث...',
    'filter': 'تصفية',
    'all': 'الكل',
    'active': 'نشط',
    'inactive': 'غير نشط',
    'draft': 'مسودة',
    'published': 'منشور',
    'archived': 'مؤرشف',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>('tr');

  // Load language from localStorage on mount
  useEffect(() => {
    const storedLang = localStorage.getItem('language') as Language;
    if (storedLang && ['tr', 'en', 'ar'].includes(storedLang)) {
      setLanguageState(storedLang);
      document.documentElement.lang = storedLang;
      if (storedLang === 'ar') {
        document.documentElement.dir = 'rtl';
      } else {
        document.documentElement.dir = 'ltr';
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
    if (lang === 'ar') {
      document.documentElement.dir = 'rtl';
    } else {
      document.documentElement.dir = 'ltr';
    }
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const value: LanguageContextType = {
    language,
    setLanguage,
    t
  };

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

